defmodule ImagePipe.Cache.InputRefreshTest do
  use ExUnit.Case, async: true
  use ExUnitProperties

  alias ImagePipe.Cache.FileSystem
  alias ImagePipe.Cache.FileSystem.Admission
  alias ImagePipe.Cache.FileSystem.Store
  alias ImagePipe.Cache.Input
  alias ImagePipe.Cache.Key
  alias ImagePipe.Cache.Resources
  alias ImagePipe.Source
  alias ImagePipe.Source.Record

  setup do
    root = Path.join(System.tmp_dir!(), "input_refresh_#{System.unique_integer([:positive])}")
    on_exit(fn -> File.rm_rf!(root) end)
    pool = [root: root, node_id: "test", max_size_bytes: 100, window_ratio: 1.0]
    start_supervised!(FileSystem.child_spec(pool))
    tasks = start_supervised!({Task.Supervisor, []})
    [{admission, _}] = Registry.lookup(FileSystem.registry_name(root), {root, "test"})
    assert :ok = Admission.await_scan(admission)
    File.mkdir_p!(root)
    path = Path.join(root, "source")
    File.write!(path, "image")
    key = %Key{hash: String.duplicate("a", 64), data: []}
    config = [input_cache: {FileSystem, pool}]
    original = record("image", 1000)
    assert :ok = Input.put(key, path, sha256("image"), original, 25, config)

    %{
      pool: pool,
      key: key,
      config: config,
      admission: admission,
      tasks: tasks,
      original: original
    }
  end

  test "an opened original is pinned under a name carrying its creation time", ctx do
    before = System.os_time(:millisecond)
    assert {:ok, pinned, lease} = Input.open(ctx.key, ctx.original, ctx.config)

    [created] =
      Regex.run(~r/\A\.image-pipe-pin-(\d+)-/, Path.basename(pinned), capture: :all_but_first)

    assert String.to_integer(created) >= before
    assert File.read!(pinned) == "image"
    Resources.release(lease)
  end

  test "a stored original stays readable after its staged file is removed", ctx do
    path = Path.join(Keyword.fetch!(ctx.pool, :root), "staged")
    File.write!(path, "staged image")
    staged = record("staged image", 1060)
    assert :ok = Input.put(ctx.key, path, sha256("staged image"), staged, 25, ctx.config)
    File.rm!(path)

    assert {:ok, pinned, lease} = Input.open(ctx.key, staged, ctx.config)
    assert File.read!(pinned) == "staged image"
    Resources.release(lease)

    assert {:ok, %{body_sha256: body_sha256}} = Store.metadata(ctx.key, ctx.pool)
    assert body_sha256 == Base.encode16(sha256("staged image"), case: :lower)
  end

  property "linked originals preserve generated bytes after the staged name is removed", ctx do
    check all bytes <- binary(min_length: 1, max_length: 65_537), max_runs: 30 do
      pool = [root: Path.join(Keyword.fetch!(ctx.pool, :root), "unbounded")]
      config = [input_cache: {FileSystem, pool}]
      path = Path.join(Keyword.fetch!(ctx.pool, :root), "linked-source")
      File.write!(path, bytes)
      source_record = record(bytes, 1_000)

      assert :ok = Input.put(ctx.key, path, sha256(bytes), source_record, 25, config)
      File.rm!(path)
      assert {:ok, pinned, lease} = Input.open(ctx.key, source_record, config)

      try do
        assert File.read!(pinned) == bytes
        assert :ok = Input.verify(ctx.key, config)
        assert {:ok, metadata} = Store.metadata(ctx.key, pool)
        assert metadata.body_byte_size == byte_size(bytes)
        assert metadata.body_sha256 == Base.encode16(sha256(bytes), case: :lower)
      after
        Resources.release(lease)
      end
    end
  end

  test "refresh preserves stored bytes and cost while updating source evidence", ctx do
    {:ok, before} = Store.metadata(ctx.key, ctx.pool)
    refreshed = record("image", 1060)
    assert :ok = Input.refresh(ctx.key, refreshed, ctx.config)
    assert {:ok, metadata} = Store.metadata(ctx.key, ctx.pool)
    assert metadata == %{before | source_record: refreshed}
  end

  test "refresh for different source bytes leaves the current record intact", ctx do
    assert :ok = Input.refresh(ctx.key, record("different", 1060), ctx.config)
    assert Input.metadata(ctx.key, ctx.config) == ctx.original
  end

  test "a refresh prepared before replacement cannot overwrite the new record", ctx do
    previous = Input.metadata(ctx.key, ctx.config)
    replacement = record("new image", 1060)
    path = Path.join(Keyword.fetch!(ctx.pool, :root), "source")
    File.write!(path, "new image")
    assert :ok = Input.put(ctx.key, path, sha256("new image"), replacement, 25, ctx.config)

    assert :ok =
             Store.refresh_source_record(ctx.key, previous, record("image", 1060), ctx.pool)

    assert Input.metadata(ctx.key, ctx.config) == replacement
  end

  test "refresh queued after invalidation cannot restore deleted metadata", ctx do
    parent = self()
    target = ctx.admission
    :sys.suspend(ctx.admission)

    {deletion, refresh} =
      try do
        deletion = queued(ctx.tasks, parent, fn -> Input.discard(ctx.key, ctx.config) end)
        assert_receive {:trace, _, :send, {:"$gen_call", _, _}, ^target}, 1000

        refresh =
          queued(ctx.tasks, parent, fn ->
            Input.refresh(ctx.key, record("image", 1060), ctx.config)
          end)

        assert_receive {:trace, _, :send, {:"$gen_call", _, _}, ^target}, 1000
        {deletion, refresh}
      after
        :sys.resume(ctx.admission)
      end

    assert Task.await_many([deletion, refresh]) == [:ok, :ok]
    assert Store.metadata(ctx.key, ctx.pool) == :miss
    assert :sys.get_state(ctx.admission).window_bytes == 0
  end

  defp queued(tasks, parent, fun) do
    Task.Supervisor.async_nolink(tasks, fn ->
      :erlang.trace(self(), true, [:send, {:tracer, parent}])
      fun.()
    end)
  end

  defp sha256(bytes), do: :crypto.hash(:sha256, bytes)

  defp record(bytes, now) do
    {:ok, source, _config} = Source.from_input({:binary, bytes}, sources: %{})
    Record.new(source, :crypto.hash(:sha256, bytes), nil, now)
  end
end
