defmodule ImagePipe.Plan do
  @moduledoc """
  Canonical request value types shared by parsing, execution, and output policy.
  """

  use Boundary,
    top_level?: true,
    deps: [ImagePipe.Format],
    exports: [
      Request,
      Request.Group,
      Request.Output,
      Output,
      Output.QualitySearch,
      Output.QualitySearch.Metric,
      Output.QualitySearch.Size,
      Output.QualitySearch.Ssimulacra2,
      Output.QualitySearch.Butteraugli,
      Output.JpegOptions,
      Output.PngOptions,
      Output.WebpOptions,
      Output.AvifOptions,
      Output.JxlOptions,
      Response,
      SourceInfo,
      Color,
      KeyData,
      Measure,
      Source,
      Source.Identity,
      Source.Path,
      Source.URL,
      Source.Object,
      Source.Reference,
      Operation,
      Operation.Background,
      Operation.Bitonal,
      Operation.Blur,
      Operation.Brightness,
      Operation.Canvas,
      Operation.Colorize,
      Operation.Contrast,
      Operation.CropGuided,
      Operation.CropRegion,
      Operation.Duotone,
      Operation.Flip,
      Operation.Gradient,
      Operation.Gray,
      Operation.Monochrome,
      Operation.Padding,
      Operation.Pixelate,
      Operation.Rotate,
      Operation.Resize,
      Operation.Saturation,
      Operation.Sharpen,
      Operation.Trim
    ]
end
