defmodule ImagePipeServer.Config.Reference do
  @moduledoc """
  Renders the configuration reference from the schemas the loader converts
  with, so it lists exactly the settings the server accepts.

  `mix image_pipe_server.gen.reference` writes it into
  `docs/server-configuration.md`, between the `reference:start` and
  `reference:end` comments.
  """

  alias ImagePipeServer.Config
  alias ImagePipeServer.Config.Sources

  @start "<!-- reference:start (generated by mix image_pipe_server.gen.reference) -->"
  @finish "<!-- reference:end -->"

  @intros [
    server:
      "The HTTP listener. Times are in milliseconds. `read_timeout` closes connections " <>
        "that send nothing for that long, idle keep-alive connections included. " <>
        "`max_connections` rounds up to a multiple of 100 above 100 connections. " <>
        "With `auth_token`, requests other than `/health` must send " <>
        "`Authorization: Bearer <token>`.",
    url:
      "How the server checks request URLs: the signing keys and the keys that decrypt " <>
        "`enc/` image paths. See [signing URLs and rotating keys](../../image_pipe/docs/signing-urls.md).",
    sources: nil,
    cache:
      "Caches on the local filesystem: `output` for processed images, `input` for " <>
        "originals. Their `root` directories must be separate, neither inside the other. " <>
        "Setting `max_size_bytes` bounds a cache and requires `node_id`. " <>
        "See [caching processed images](../../image_pipe/docs/caching-processed-images.md).",
    processing:
      "Defaults and limits for every image the server processes. The limits on " <>
        "originals and results are described in " <>
        "[limiting work per request](../../image_pipe/docs/deployment.md).",
    pool:
      "How many images are processed at once, and how long requests wait for a turn. " <>
        "Times are in milliseconds. Without this section, every request is processed " <>
        "immediately. See [limiting concurrent processing](../../image_pipe/docs/processing-controls.md).",
    http:
      "Response settings: the CORS origin, whether requests may ask for debug headers, " <>
        "and the HTTP cache headers. See [serving images through a CDN](../../image_pipe/docs/serving-through-a-cdn.md).",
    telemetry:
      "`log_level` logs each request and its stages at that level. Failures log at " <>
        "`warning`. With `trust_traceparent`, a request with a W3C `traceparent` " <>
        "header joins the caller's trace when [tracing](server-deployment.md#tracing) " <>
        "is on. Any client can send that header."
  ]

  @doc "The reference as Markdown."
  @spec markdown() :: String.t()
  def markdown do
    Config.schema()
    |> Enum.map_join("\n", fn {section, spec} -> section(section, Keyword.fetch!(spec, :type)) end)
    |> then(&Regex.replace(~r/\n{3,}/, &1, "\n\n"))
    |> String.trim_trailing()
    |> Kernel.<>("\n")
  end

  @doc "Replaces the reference between the markers in `document`."
  @spec replace(String.t()) :: String.t()
  def replace(document) do
    [before, rest] = String.split(document, @start, parts: 2)
    [_old, after_reference] = String.split(rest, @finish, parts: 2)
    before <> @start <> "\n\n" <> markdown() <> "\n" <> @finish <> after_reference
  end

  @doc "The reference between the markers in `document`."
  @spec extract(String.t()) :: String.t()
  def extract(document) do
    [_before, rest] = String.split(document, @start, parts: 2)
    [reference, _after] = String.split(rest, @finish, parts: 2)
    reference |> String.trim_leading("\n") |> String.trim_trailing("\n") |> Kernel.<>("\n")
  end

  defp section(:sources, _type), do: sources()

  defp section(name, {:convert, _fun, schema}) do
    """
    ### `[#{name}]`

    #{Keyword.fetch!(@intros, name)}

    #{table(schema)}
    """
  end

  defp sources do
    adapters =
      Enum.map_join(Sources.adapter_schemas(), "\n", fn {adapter, schema} ->
        """
        #### `adapter = "#{adapter}"`

        #{table(schema)}
        """
      end)

    [{:static, static} | providers] = Sources.credential_schemas()

    provider_tables =
      Enum.map_join(providers, "\n", fn {provider, schema} ->
        """
        `provider = "#{provider}"`:

        #{table(schema)}
        """
      end)

    """
    ### `[sources.<name>]`

    One table per source. The table name is the source's name. Besides
    `adapter` and `match`, a source takes its adapter's options.

    #{table(Sources.mount_schema())}
    #{adapters}
    #### S3 `credentials`

    Static credentials:

    #{table(Enum.map(static, fn {key, spec} -> {:"static.#{key}", spec} end))}
    Or a credential `provider` and its options. `assume_role` takes `base`
    credentials in the same forms. `container_credentials` without
    `relative_uri`, `full_uri`, or `auth_token` takes all three from
    `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI`, `AWS_CONTAINER_CREDENTIALS_FULL_URI`,
    and `AWS_CONTAINER_AUTHORIZATION_TOKEN`. `web_identity` fills each of
    `token_file`, `role_arn`, `region`, and `role_session_name` that the
    table leaves out, from `AWS_WEB_IDENTITY_TOKEN_FILE`, `AWS_ROLE_ARN`,
    `AWS_REGION`, and `AWS_ROLE_SESSION_NAME` respectively.

    #{provider_tables}
    """
  end

  defp table(schema) do
    {rows, elixir_only} =
      schema |> rows("") |> Enum.split_with(&match?({_name, _type, _default}, &1))

    header = "| Key | Type | Default |\n| --- | --- | --- |\n"

    body =
      Enum.map_join(rows, "\n", fn {name, type, default} ->
        "| `#{name}` | #{type} | #{if default, do: "`#{default}`", else: ""} |"
      end)

    note =
      case elixir_only do
        [] ->
          ""

        names ->
          "\nElixir only: " <> Enum.map_join(names, ", ", fn {name} -> "`#{name}`" end) <> ".\n"
      end

    header <> body <> "\n" <> note
  end

  defp rows(schema, prefix) do
    Enum.flat_map(schema, fn {key, spec} ->
      name = prefix <> Atom.to_string(key)
      type = Keyword.fetch!(spec, :type)

      type =
        if Keyword.has_key?(spec, :keys), do: {:table, Keyword.fetch!(spec, :keys)}, else: type

      rows_for(name, type, Keyword.get(spec, :default))
    end)
  end

  defp rows_for(name, {:table, schema}, _default), do: rows(schema, name <> ".")

  defp rows_for(name, {:convert, _fun, schema}, _default) when is_list(schema),
    do: rows(schema, name <> ".")

  defp rows_for(name, {:map, _key, {:convert, _fun, schema}}, _default) when is_list(schema),
    do: rows(schema, name <> ".<name>.")

  defp rows_for(name, {:or, types} = type, default) do
    nested =
      for {:convert, _fun, schema} <- types,
          is_list(schema),
          row <- rows(schema, name <> "."),
          do: row

    [row(name, type, default) | nested]
  end

  defp rows_for(name, type, default), do: [row(name, type, default)]

  defp row(name, type, default) do
    case describe(type) do
      nil -> {name}
      description -> {name, description, toml(default)}
    end
  end

  defp describe(:string), do: "string"
  defp describe(:integer), do: "integer"
  defp describe(:pos_integer), do: "integer > 0"
  defp describe(type) when type in [:non_neg_integer, :timeout], do: "integer ≥ 0"
  defp describe(:float), do: "number"
  defp describe(:boolean), do: "boolean"
  defp describe({:in, first..last//_step}), do: "integer #{first}–#{last}"

  defp describe({:in, choices}) do
    choices
    |> Enum.reject(&(is_nil(&1) or is_boolean(&1)))
    |> Enum.map_join(" or ", fn
      choice when is_atom(choice) -> "`\"#{choice}\"`"
      choice -> "`#{choice}`"
    end)
  end

  defp describe({:list, type}), do: with_inner("array of ", type)
  defp describe({:map, _key, type}), do: with_inner("table of ", type)

  defp describe({:tuple, [{:in, tags}, type]}) do
    Enum.map_join(tags, " or ", &"`{ #{&1} = … }`") <> " (#{describe(type)})"
  end

  defp describe({:or, types}) do
    types
    |> Enum.reject(&is_nil/1)
    |> Enum.map(&describe/1)
    |> Enum.reject(&is_nil/1)
    |> case do
      [] -> nil
      descriptions -> Enum.join(descriptions, " or ")
    end
  end

  defp describe({:custom, _module, _function, _args}), do: "string"
  defp describe({:convert, _fun, description}) when is_binary(description), do: description
  defp describe({:convert, _fun, schema}) when is_list(schema), do: "table"
  defp describe(_type), do: nil

  defp with_inner(prefix, type) do
    case describe(type) do
      nil -> nil
      inner -> prefix <> inner
    end
  end

  defp toml(value) when is_binary(value), do: inspect(value)
  defp toml(value) when is_number(value) or is_boolean(value), do: to_string(value)
  defp toml(nil), do: nil
  defp toml(value) when is_atom(value), do: ~s("#{value}")
  defp toml(value) when is_struct(value), do: nil

  defp toml(value) when is_map(value) do
    value |> Enum.sort() |> inline_table()
  end

  defp toml([]), do: "[]"

  defp toml(value) when is_list(value) do
    if Keyword.keyword?(value), do: value |> Enum.sort() |> inline_table(), else: array(value)
  end

  defp toml(_value), do: nil

  defp array(values) do
    rendered = Enum.map(values, &toml/1)
    if Enum.any?(rendered, &is_nil/1), do: nil, else: "[" <> Enum.join(rendered, ", ") <> "]"
  end

  defp inline_table(pairs) do
    rendered = Enum.map(pairs, fn {key, value} -> {key, toml(value)} end)

    if Enum.any?(rendered, fn {_key, value} -> is_nil(value) end),
      do: nil,
      else:
        "{ " <> Enum.map_join(rendered, ", ", fn {key, value} -> "#{key} = #{value}" end) <> " }"
  end
end
